SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
SCREEN_TITLE = 'Platformer Game'

TILE_SCALING = 0.5
CHARACTER_SCALING = TILE_SCALING * 1.5
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SCALING

PLAYER_MOVEMENT_SPEED = 7
GRAVITY = 1.5
PLAYER_JUMP_SPEED = 30

PLAYER_START_X = 2
PLAYER_START_Y = 1

RIGHT_FACING = 0
LEFT_FACING = 1

LAYER_NAME_PLATFORMS = "Platforms"
LAYER_NAME_BACKGROUND = "Background"
LAYER_NAME_FOREGROUND = "Foreground"
LAYER_NAME_LADDERS = "Ladders"
LAYER_NAME_COINS = "Coins"
LAYER_NAME_DEATH = "Death"
LAYER_NAME_FINISH = "Finish"
LAYER_NAME_ENEMIES = "Enemies"
LAYER_NAME_PLAYER = "Player"
